# This is a basic workflow to help you get started with Actions

name: Deploy APP

on:
  push:
    branches: [ stopped ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
  
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.2
      with:
        node-version: 12.x
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1
    - name: Get env stuff
      run: |
        cd $GITHUB_WORKSPACE
        aws s3 cp s3://${{ secrets.SECRETS_BUCKET }}/${GITHUB_REF##*/}/${GITHUB_REF##*/}.json .
    
    - name: Cache node modules
      uses: actions/cache@v1
      with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

    - name: Dependency
      run: npm install serverless

    - name: Geronimo
      run: npx sls deploy --stage ${GITHUB_REF##*/} >> slsoutput.txt